### ISSUE TITLE
Is it possible to strip query strings from logs?

### ISSUE THREAD

**Issue by daniel-ac-martin** [HMPO/hmpo-logger#14]
I'd really like to use this module in our project, but we have an annoying requirement to remove query strings from our logs.

Is this currently possible with hmpo-logger?

**Comment by HughePaul** [comment]
This could be added as an option

**Comment by HughePaul** [comment]
I've made a PR for a token function that returns a stripped URL
https://github.com/UKHomeOffice/passports-logger/pull/16

this could be used by updating the meta that is logged in the config when configuring the logger:
{
  meta: {
   request: 'strippedRequest'
  }
}
