### ISSUE TITLE
npm Vulnerability in logger package

### ISSUE THREAD

**Issue by MartinDM** [HMPO/hmpo-logger#43]
We're using this package as a dependency in our app, but it seems it's using a vulnerable version of package `winston`.
When updating this dependency, the packages' `test` command fails.

I'm assessing the work needed in fixing this for a possible PR, but is anyone currently working (or aware of) updating the dependencies of this package to pass tests using the latest, secured version of Winston?

Refs:
https://snyk.io/test/npm/hmpo-logger/4.1.3

Thank in advance!
Martin

**Comment by HughePaul** [comment]
I've been looking at this today, either upgrading the code to use Winston 3, or not using Winston as a logging backend at all

**Comment by MartinDM** [comment]
Great, Paul.
Is it something you're looking to update the package with as it's holding up a couple of stories for now, so thinking of options...
If you reckon it's something you can have fixed fairly soon (likely more easily than me as you're familiar with it!) then we can hold those stories for a bit...

Alternatively I'd be able to make a new work item to help take a look too, and try to get that in our current sprint to free those up. Depend show much work you reckon you'll need to do/how long. it could be - what would you suggest?
Thanks for picking this up so soon too 👍

**Comment by HughePaul** [comment]
major version 6.0.0 has been released that no longer used winston. This version should be drop in compatible, but the pretty-print console logging will look slightly different.
